SECRET_KEY = 'development key'
DB_IP = 'localhost'
DB_PORT = 6379
FITNESSE_ROOT = '/Users/ZQ/develop/eclipsecode/stability/Fitnesse/FitNesseRoot/'
# FITNESSE_ROOT = '/Users/ZQ/develop/eclipsecode/caipiao/Fitnesse/FitNesseRoot/SlimTest'
MYSQL_HOST = 'localhost'
MYSQL_USERNAME = 'root'
MYSQL_PWD = 'zq920320'
MYSQL_PORT = 3306
MYSQL_DB = 'stability'
